"""init analysis tables

Revision ID: 405f88e59fcc
Revises: bcedcdc4faf6
Create Date: 2025-09-27 10:32:39.555646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405f88e59fcc'
down_revision: Union[str, None] = 'bcedcdc4faf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('risk', sa.JSON(), nullable=True))
    op.add_column('analysis', sa.Column('ta', sa.JSON(), nullable=True))
    op.add_column('analysis', sa.Column('derivs', sa.JSON(), nullable=True))
    op.add_column('analysis', sa.Column('onchain', sa.JSON(), nullable=True))
    op.add_column('analysis', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('analysis', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('analysis', 'interval',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('analysis', 'signal',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('uq_analysis_entry', 'analysis', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_analysis_entry', 'analysis', ['symbol', 'interval', 'created_at'])
    op.alter_column('analysis', 'signal',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('analysis', 'interval',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('analysis', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('analysis', 'notes')
    op.drop_column('analysis', 'onchain')
    op.drop_column('analysis', 'derivs')
    op.drop_column('analysis', 'ta')
    op.drop_column('analysis', 'risk')
    # ### end Alembic commands ###
