"""change created_at to client side

Revision ID: 7f3c88e7b5e4
Revises: db4e8f19d82c
Create Date: 2025-09-27 08:18:25.107807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3c88e7b5e4'
down_revision: Union[str, None] = 'db4e8f19d82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
