"""make created_at not null

Revision ID: f6cb954fbcc1
Revises: 7f3c88e7b5e4
Create Date: 2025-09-27 10:45:14.503543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = 'f6cb954fbcc1'
down_revision: Union[str, None] = '7f3c88e7b5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE analysis SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column(
        'analysis',
        'created_at',
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now()
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
